//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

public class University
{
	public virtual IEnumerable<Staff> Staff
	{
		get;
		set;
	}

	public virtual IEnumerable<Student> Student
	{
		get;
		set;
	}

}

